#!/bin/bash

rootpath=$(pwd)

# folderlist generated by 0metaNCL_gwasList.R

ncl4folder="PCspeAMLHRC"

# no. phenos
#nophenos=(`cat ${listdir}/${prefix}_chr1pheno.lst | awk '{print $1}' `)

# declare -a nophenos=('status' 'Normal' 'CBF' 'Trans' 'Complex' 't15_17' 'del5_7' 'Trisomies' 'Any.Monosomy' 'monosomal.karyotype' 'abnormality' 'anyTriMon' 'transNOt1517')

declare -a nophenos=('status' 'Normal' 'CBF' 'Trans' 'Complex' 't15_17' 'del5_7' 'Trisomies')

#Trisomies
#Any.Monosomy
#monosomal.karyotype
echo ""
echo "no. phenos are ${#nophenos[@]}"
echo ""
echo ${nophenos[@]}
echo ${#nophenos[@]}

for ((i=0; i<${#nophenos[@]}; i++))
do

subFile6=${nophenos[i]}_${ncl4folder}LZ0.slurm
cat > ${subFile6}<<EOF
#!/bin/bash
#SBATCH -A jamgaml
#SBATCH --partition=defq,long,bigmem
#SBATCH --time=01:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=8G
#SBATCH --exclude=ln03,sb017
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=Wei-Yu.Lin@newcastle.ac.uk
#SBATCH --chdir=${rootpath}/Hitsmeta

module load R/3.3.1-intel-2017.03-GCC-6.3
module load HTSlib/1.4.1-intel-2017.03-GCC-6.3

Rscript --vanilla ${rootpath}/lz_hitsmetaHRC.R "${nophenos[i]}" "${ncl4folder}"

EOF

command6="sbatch ${subFile6}"
jid6=$($command6 | awk ' { print $4 }')

#sleep 0.5

subFile2=${nophenos[i]}_${ncl4folder}LZ1.slurm
cat > ${subFile2}<<EOF
#!/bin/bash
#SBATCH -A jamgaml
#SBATCH --partition=defq,short,long,bigmem
#SBATCH --time=00:10:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=8G
#SBATCH --exclude=ln03,sb017
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=Wei-Yu.Lin@newcastle.ac.uk
#SBATCH --chdir=${rootpath}/Hitsmeta

module load R/3.3.1-intel-2017.03-GCC-6.3

pheno=(\$(cat ${nophenos[i]}*lzname.txt | awk '{print \$1}'))
study=(\$(cat ${nophenos[i]}*lzname.txt | awk '{print \$2}'))
snps=(\$(cat ${nophenos[i]}*lzname.txt | awk '{print \$3}'))
chr=(\$(cat ${nophenos[i]}*lzname.txt | awk '{print \$4}'))
pos=(\$(cat ${nophenos[i]}*lzname.txt | awk '{print \$5}'))

if [ \${#snps[@]} -eq 0 ]
then

exit

fi

for ((i=0; i<\${#snps[@]}; i++))
do

bash /nobackup/proj/jamgaml/LZtest/lzsubmit.sh \${pheno[i]} \${study[i]} \${snps[i]} \${chr[i]} \${pos[i]}


done


EOF

sbatch --dependency=afterok:${jid6} ${subFile2}


done
